services:
  api:
    build: .
    container_name: demoapi-sesion22
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      APP_ENV: prod
      APP_VERSION: 1.0.0

  db:
    image: postgres:16
    container_name: examen-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
