app.environment=DEV
app.entorno=DEV

app.message=Entorno de desarrollo activo
app.mensaje=Entorno de desarrollo activo

app.version=1.0.0
app.version-sistema=1.0.0

app.institucion=Universidad Nacional Agraria de la Selva - FIIS
app.soporte=soporte-dev@unas.edu.pe
app.modo=desarrollo
app.limite-usuarios=50
app.variante-cliente=DEV