app.environment=TEST
app.entorno=TEST

app.message=Entorno de pruebas activo
app.mensaje=Entorno de pruebas activo

app.version=1.0.0
app.version-sistema=1.0.0

app.institucion=Universidad Nacional Agraria de la Selva - FIIS
app.soporte=soporte-test@unas.edu.pe
app.modo=pruebas
app.limite-usuarios=10
app.variante-cliente=TEST