app.environment=PROD
app.entorno=PROD

app.message=Entorno de produccion activo
app.mensaje=Entorno de produccion activo

app.version=1.0.0
app.version-sistema=1.0.0

app.institucion=Universidad Nacional Agraria de la Selva - FIIS
app.soporte=soporte@unas.edu.pe
app.modo=produccion
app.limite-usuarios=500
app.variante-cliente=PROD