app.entorno=test
app.mensaje=Entorno de pruebas FIIS
app.version=1.0-TEST
app.soporte=soporte-test@unas.edu.pe

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration