spring.application.name=examen-parcial1-const-sw2
server.port=${APP_PORT:8080}
app.version=${APP_VERSION:1.0.0}
app.environment=${APP_ENV:local}
app.message=Configuracion base activa
spring.messages.basename=messages
spring.messages.encoding=UTF-8
