spring.application.name=examen-parcial1-const-sw2
server.port=8080

spring.messages.basename=messages
spring.messages.encoding=UTF-8














spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration