# Perfil Docker - Sesion 20
spring.application.name=examen-parcial1-const-sw2
server.port=8080

# Logging en contenedor
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
