spring.application.name=examen-parcial1-const-sw2
server.port=8080
spring.profiles.active=dev

app.institucion=Universidad Nacional Agraria de la Selva
app.modo=ACADEMICO
app.limite-usuarios=100
app.version-sistema=1.0.0
app.notificacion.proveedor=mock

app.variante-cliente=VIP
